language: scala

scala:
  - 2.11.12

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalastyle coverage test coverageReport

env:
  global:
    secure: q7DemjHxTB1Nk2QXowQjrXMy+3Op4OfmgxYmaEnpI4pN2fagfH5hG6UF+gtIUo3tjzKcZH0fq0SH8D1/a9Mz2s+TT2sSk+YyrzhaaOkJwE0YY1qPtxzfsmHyCfmSx0tki13TPhwzcc4jxhdhDhY8eS8XQq0h+XbEK9/y7gJYOcKDfh+9vDFRPch0Al7FYli18BezCzc+h0l7YV8KrC+J6bipa4RaQL2btkrxiHLL1ajOQdGL932gNXSfWt7x6copSsU9uQPB/BA9BCUTVZ1bl3NU32DhzzIUpn7p9TjTbWJk9je6DFRe098z8i2Bu6UGqidLA14255HKHC4E4eaSlyW6knRhfMDjZTJISIkli6wbHRVi6V1EYrrl64CUJFeboCwsiEE8G+H9oj7R79HDLhN9XA6M0CB/iKOYQXOlAPKd+QGWVaWBJA7QuP28PoEvs6qM5of8gD5sO39/Q62tlF9l/HMY6IjWWsbYIOWX7egT2SCHOJY39Rj+UU/gr/euCisnUISSPRFDgc3/OMZh8DUbOaaO4MSLYyBJM2t+Tq4yaWHABB8P0FJO1sMZ8q4nwmWT+zcZjpQHz68xxQ2Zcrv4kAN0nxz7zAltGcESdxZMmN/YSSauVSEoEgV90Iyqtvofe3NrrDi2DOEV7KKbDqbXW1awHAUwnT9N5snnJbM=
